### ISSUE TITLE
使用 Cloudflare Pages 部署报错

### ISSUE THREAD

**Issue by Minority2310** [izhichao/vitepress-theme-minimalism#2]
大佬好，很喜欢你的这个主题，我想使用 Cloudflare Pages 部署，但是遇到以下问题：

[VitePress官方文档](https://vitepress.dev/zh/guide/deploy) 部署有截图中的前提要求和 [Cloudflare部署](https://vitepress.dev/zh/guide/deploy#netlify-vercel-cloudflare-pages-aws-amplify-render) 配置
![Clip_2024-03-18_17-59-28](https://github.com/izhichao/vitepress-theme-minimalism/assets/73096231/32892fe2-0f5f-4e8b-894e-f3691b5f79d9)
![Clip_2024-03-18_18-06-24](https://github.com/izhichao/vitepress-theme-minimalism/assets/73096231/053fd39f-2163-41c7-9a64-b2ffc1cfafb1)

我未进行改动，fork 本项目进行测试，在部署时会报错
![Clip_2024-03-18_18-07-45](https://github.com/izhichao/vitepress-theme-minimalism/assets/73096231/7aa134a3-b2e1-427a-918d-47f9b1ea7e0c)
![image](https://github.com/izhichao/vitepress-theme-minimalism/assets/73096231/5492bca5-ce78-46c2-8beb-ad47371f332e)

请问我应该做哪些更改才可以部署？

**Comment by izhichao** [comment]
1. Cloudflare Pages 部署时，`根目录（高级）-> 路径` 不需要填写
2. VitePress 配置文件 `vitepress/config.ts` 中移除 `base: '/vitepress-theme-minimalism/'`

**Comment by Minority2310** [comment]
> 1. Cloudflare Pages 部署时，`根目录（高级）-> 路径` 不需要填写
> 2. VitePress 配置文件 `vitepress/config.ts` 中移除 `base: '/vitepress-theme-minimalism/'`

按照大佬的配置已经成功了，非常感谢！！！
