### ISSUE TITLE
文章 frontmatter 使用 permalink，访问时找不到文章

### ISSUE THREAD

**Issue by Minority2310** [izhichao/vitepress-theme-minimalism#3]
大佬，我在 frontmatter 使用 permalink 如下
```
---
title: Cloudflare Pages 部署 vitepress 博客
datetime: '2024-07-31 16:32:54'
permalink: posts/1a4aa9
outline: deep
pinned: true
tags: 
  - vitepress
  - cloudflare
  - 博客
---
```
部署后访问 https://wiki.minority2310.com/posts/1a4aa9 显示页面找不到，请问是哪个配置有问题呢？

**Comment by izhichao** [comment]
`permalink: posts/1a4aa9` 修改为 `permalink: /posts/1a4aa9`

**Comment by Minority2310** [comment]
> `permalink: posts/1a4aa9` 修改为 `permalink: /posts/1a4aa9`

访问正常了，感谢大佬！！！
